plugins {
    id 'java'
    id 'application'
    id 'com.grishka.OriginMod'
}

group = 'me.grishka'
version = '1.0-SNAPSHOT'

originMod {
    MODID = 'helloMod'
    MODVERSION = '1.0.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    mainClass = 'com.grishka.OriginLoader.helloMod.OriginMod'
}

repositories {
    mavenCentral()
    flatDir { 
        // We point this to the Loader's lib folder for LWJGL
        dirs '../../src/lib' 
    }
    flatDir {
        // We point this to the Loader's build folder for the JAR
        dirs '../../build/libs'
    }
}

dependencies {
    // FIX: Using fileTree to correctly find the JAR without wildcard errors
    compileOnly fileTree(dir: '../../build/libs', include: ['*.jar'])
    
    // LWJGL dependencies
    compileOnly name: 'lwjgl'
    compileOnly name: 'lwjgl_util'
}

jar {
    manifest {
        attributes 'Origin-Mod-Class': 'com.grishka.OriginLoader.helloMod.OriginMod'
    }

}